export const RACE_MODES={PLAYER_VS_AI:"player-vs-ai",PLAYER_VS_PLAYER:"player-vs-player",AI_VS_AI:"ai-vs-ai"};
export const RACE_CONFIG={trackLength:9000,laps:3,maxSpeed:430,acceleration:235,brake:330,drag:38,offroadDrag:185,steerSpeed:1.45,countdown:3,driftGrip:2.8,handbrakeDrag:95};
export function curveAt(distance){const z=distance%RACE_CONFIG.trackLength;return Math.sin(z/620)*.42+Math.sin(z/1450+.7)*.58+Math.sin(z/270)*.09}
export function elevationAt(distance){return Math.sin(distance/850)*42+Math.sin(distance/330)*12}
const colors=["#5ff0bb","#ff7187","#ffd166","#72a7ff"];
export function createRaceState(options={}){const config={...RACE_CONFIG,...options},cars=colors.map((color,id)=>({id,color,x:[-.32,.34,-.58,.62][id],distance:-id*55,speed:0,lap:0,finished:false,finishTime:null,rank:id+1,ai:true,steer:0,drift:0,driftScore:0,combo:1,bestDrift:0}));return{config,cars,running:false,countdown:config.countdown,time:0,winner:null,finishedOrder:[],mode:RACE_MODES.PLAYER_VS_AI,difficulty:"normal"}}
export function humanCarIds(mode){if(mode===RACE_MODES.PLAYER_VS_PLAYER)return[0,1];if(mode===RACE_MODES.PLAYER_VS_AI)return[0];return[]}
function aiInput(state,car){const skill={easy:.77,normal:.9,hard:1}[state.difficulty]||.9,targetSpeed=state.config.maxSpeed*skill;let target=Math.sin((car.distance+car.id*730)/1100)*.48;const curve=curveAt(car.distance+420);target-=curve*.42;for(const other of state.cars){if(other===car)continue;const gap=other.distance-car.distance;if(gap>0&&gap<190&&Math.abs(other.x-target)<.28)target+=other.x<0?.42:-.42}const steering=Math.abs(target-car.x)<.035?0:Math.sign(target-car.x);return{left:steering<0,right:steering>0,accelerate:car.speed<targetSpeed,brake:car.speed>targetSpeed+30,handbrake:Math.abs(curve)>.62&&car.speed>190}}
function updateCar(state,car,input,dt){const c=state.config;if(car.finished)return;const throttle=input.accelerate?c.acceleration:0,braking=input.brake?c.brake:0,steering=(input.right?1:0)-(input.left?1:0),speedRatio=car.speed/c.maxSpeed;car.speed+=throttle*dt-braking*dt-c.drag*dt-(input.handbrake?c.handbrakeDrag*dt:0);if(Math.abs(car.x)>1)car.speed-=c.offroadDrag*dt;car.speed=Math.max(0,Math.min(c.maxSpeed,car.speed));car.steer+=(steering-car.steer)*Math.min(1,dt*9);const driftTarget=input.handbrake&&Math.abs(car.steer)>.1&&car.speed>105?car.steer*.92:car.steer*speedRatio*.28;car.drift+=(driftTarget-car.drift)*Math.min(1,dt*(input.handbrake?c.driftGrip:5.5));car.x+=(car.steer+car.drift*.72)*c.steerSpeed*(.3+.7*speedRatio)*dt;car.x-=curveAt(car.distance+180)*car.speed*dt*.00052;car.x=Math.max(-1.42,Math.min(1.42,car.x));const activeDrift=Math.abs(car.drift)>.2&&car.speed>120;if(activeDrift){car.combo=Math.min(5,car.combo+dt*.32);car.driftScore+=Math.abs(car.drift)*car.speed*car.combo*dt;car.bestDrift=Math.max(car.bestDrift,car.driftScore)}else if(Math.abs(car.drift)<.08)car.combo=Math.max(1,car.combo-dt*1.8);car.distance+=car.speed*dt*(1-Math.abs(car.drift)*.08);car.lap=Math.max(0,Math.floor(car.distance/c.trackLength));if(car.distance>=c.trackLength*c.laps){car.finished=true;car.finishTime=state.time;state.finishedOrder.push(car.id);if(state.winner===null)state.winner=car.id}}
function collisions(state){for(let a=0;a<state.cars.length;a++)for(let b=a+1;b<state.cars.length;b++){const one=state.cars[a],two=state.cars[b],gap=Math.abs(one.distance-two.distance);if(gap>42||Math.abs(one.x-two.x)>.2)continue;const direction=one.x<=two.x?-1:1;one.x+=direction*.06;two.x-=direction*.06;const slow=Math.min(one.speed,two.speed)*.72;one.speed=Math.min(one.speed,slow);two.speed=Math.min(two.speed,slow)}}
function ranks(state){[...state.cars].sort((a,b)=>b.distance-a.distance).forEach((car,index)=>car.rank=index+1)}
export function updateRace(state,dt,inputs=[]){if(!state.running||state.winner!==null)return state;dt=Math.min(Math.max(dt,0),.06);state.time+=dt;if(state.countdown>0){state.countdown=Math.max(0,state.countdown-dt);return state}const humans=humanCarIds(state.mode);for(const car of state.cars){car.ai=!humans.includes(car.id);const input=car.ai?aiInput(state,car):inputs[car.id]||{};updateCar(state,car,input,dt)}collisions(state);ranks(state);if(state.winner!==null)state.running=false;return state}
export class RacingGame{constructor(options={}){this.state=createRaceState(options)}get config(){return this.state.config}setMode(mode){if(Object.values(RACE_MODES).includes(mode)){const{difficulty}=this.state;this.state=createRaceState(this.config);this.state.mode=mode;this.state.difficulty=difficulty}}setDifficulty(value){this.state.difficulty=["easy","normal","hard"].includes(value)?value:"normal"}setLaps(value){const laps=Math.max(1,Math.min(5,Number(value)||3)),{mode,difficulty}=this.state;this.state=createRaceState({...this.config,laps});this.state.mode=mode;this.state.difficulty=difficulty}play(){if(this.state.winner!==null)this.newRace();this.state.running=true}pause(){this.state.running=false}newRace(){const{mode,difficulty}=this.state,config=this.config;this.state=createRaceState(config);this.state.mode=mode;this.state.difficulty=difficulty}update(dt,inputs){return updateRace(this.state,dt,inputs)}}