# Exemple pour /etc/apache2/sites-available/playground.conf
<VirtualHost *:80>
    ServerName playground.local
    DocumentRoot /var/www/html/playground

    KeepAlive On
    MaxKeepAliveRequests 100
    KeepAliveTimeout 2

    <Directory /var/www/html/playground>
        Options -Indexes
        AllowOverride All
        Require all granted
        DirectoryIndex index.html
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/playground-error.log
    CustomLog ${APACHE_LOG_DIR}/playground-access.log combined
</VirtualHost>
